### ISSUE TITLE
warning should be returned as good

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#16]
warning should be returned as good or success but should still list the warning ingredients under the good ingredients.
http://isitcg.herokuapp.com/Home/Results/N33s6tDMlEGdTOdBVspGbQ

**Comment by josephgardner** [comment]
So the "overall" result should yes or no.
* danger = no
* warning = yes
* success = yes

**Comment by josephgardner** [comment]
Functions to spec
