### ISSUE TITLE
Yes results should share the good qualities

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#5]
When a yes result comes up ... I would like it to say "Yes, this product is CG approved and the following ingredients have been recognized as"
Gentle Cleansers:
- example

Moisturizing Alcohols:
- example

Water Soluble Silicones:
- example

Proteins:
- example

Waxes:
- example

Humectants (need to add this category):
- example

**Comment by josephgardner** [comment]
Functioning to spec
