### ISSUE TITLE
Add Trimethylsiloxyamodimethicone

### ISSUE THREAD

**Issue by melissamcewen** [josephgardner/isitcg#58]
First of all, I love the app and share it all over the place. Saw this lovely ingredient in a product today and didn't come up in your app. I'm happy to contrib/write docs if you are interested. I don't know C# but wouldn't mind learning.

**Comment by josephgardner** [comment]
Glad you found the source :) I will gladly accept pull requests. To add a new ingredient, you just need to edit the [ingredientrules.json](https://github.com/josephgardner/isitcg/blob/master/src/isitcg.web/ingredientrules.json) file. 

To make sure the list is accurate, do you have a reference for this ingredient that says it is/is not CG?

**Comment by melissamcewen** [comment]
I think I know chemistry about as well as I know C# lol, but this list has it under "Water-insoluble silicones":
http://science-yhairblog.blogspot.com/2014/04/silicone-ingredient-solubility-list.html

**Comment by josephgardner** [comment]
[This site](https://www.livecurlylivefree.com/product-ingredients) seems to agree but has a caveat:

> Silicones that are not soluble in water, but whose chemical properties allow it to repel further deposit, helping to prevent buildup (although they will still lock moisture out of the hair and require a surfactant to remove)

@lmgardner want to make a call?

**Comment by lmgardner** [comment]
I trust anything the sciencey-hairblog says. We probably need to cross reference her list with our list and add anything that is missing. If you want to do that to help, Melissa, that would be awesome. We just moved across the country so might not get to it right away.

**Comment by josephgardner** [comment]
Done. @melissamcewen please submit a PR for any additional changes!
