### ISSUE TITLE
No results should share the bad qualities and the good qualities

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#6]
If a no result comes up, it should say ... "Sorry, this product is not CG approved because it contains the following ingredients:"
Sulfates:
- example

Silicones:
- example

Waxes:
- example

Drying Alcohols:
- example

This product contains the following CG approved ingredients

Gentle Cleansers:
- example

Moisturizing Alcohols:
- example

Water Soluble Silicones:
- example

Proteins:
- example

Waxes:
- example

Humectants (need to add this category):
- example

**Comment by josephgardner** [comment]
Functioning to spec
