### ISSUE TITLE
slashes are acting as commas

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#61]
slashes are acting as commas and splitting the ingredient into multiple ingredients

**Comment by lmgardner** [comment]
example: Bis-Amino PEG/PPG-41/3 Aminoethyl PG-Propyl Dimethicone

**Comment by josephgardner** [comment]
This was introduced in #9. How should we handle slashes?

**Comment by josephgardner** [comment]
e53ddb03a1880f8f7defbc10b3e9b57a56fc2685

**Comment by lmgardner** [comment]
Try to match the entire string first, if that’s not a match then test each individual piece. Count it if any match.

This will fix #9 because it will fix the beeswax part

Sent from my iPhone

On Jan 23, 2018, at 7:25 PM, josephgardner <notifications@github.com<mailto:notifications@github.com>> wrote:


This was introduced in #9<https://github.com/josephgardner/isitcg/issues/9>. How should we handle slashes?

**Comment by josephgardner** [comment]
Fixed with #63
