### ISSUE TITLE
Add Humectant category (CG Approved)

### ISSUE THREAD

**Issue by lmgardner** [josephgardner/isitcg#7]
- Glycerin
- Propylene glycol
- Honey
- Agave nectar
- Sorbitol
- Sodium PCA
- Panthenol
- Hydrolyzed silk protein
- Fructose

**Comment by josephgardner** [comment]
Can you provide a description that describes this category?

**Comment by josephgardner** [comment]
Also, is this a "good", "bad", or "warning" category?

**Comment by lmgardner** [comment]
Yes with a warning

Sent from my iPhone

On Apr 27, 2017, at 9:42 PM, josephgardner <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, is this a "good", "bad", or "warning" category?

**Comment by josephgardner** [comment]
OK, just need a description

**Comment by lmgardner** [comment]
A humectant absorbs moisture and keeps a moisture balance in the hair and skin. Humectants will search for moisture in your own hair too. Therefore, in areas where it may be hot, but dry, these products may actually do more bad than good. In the right condition, humectantsare materials used in products to moisturize dry or damaged hair.  They promote moisture retention by attracting water molecules from the local environment and binding them to specific sites along their structure.

**Comment by lmgardner** [comment]
Learn more here:

**Comment by lmgardner** [comment]
Learn more here: https://www.naturallycurly.com/curlreading/wavy-hair-type-2/the-411-on-dew-points-humectants/
